// site/src/routes/artists/[slug]/+page.svelte
<script lang="ts">
    import Image from "$lib/components/Image.svelte";
    import ReleaseGrid from "$lib/components/ReleaseGrid.svelte";
    import SocialLink from "$lib/components/SocialLink.svelte";
    import type { PageProps } from "./$types";

    let { data }: PageProps = $props();
    let { artist } = data;
</script>

<div class="container flex flex-col gap-10">
    <section class="flex flex-col gap-y-5 gap-x-10 sm:grid sm:grid-cols-12">
        <div class="sm:col-span-4">
            <Image image={artist.images[0]} format="xlarge" />
        </div>

        <div class="sm:col-span-8">
            <h1 class="flex flex-col gap-2">
                {artist.name}
                <div class="flex gap-4">
                    {#each artist.links as link (link)}
                        <SocialLink
                            href={link.link}
                            type={link.linktype}
                            external
                        />
                    {/each}
                </div>
            </h1>

            <div>{@html artist.bio}</div>
        </div>
    </section>

    {#if artist.releases.length > 0}
        <section>
            <h2>Releases</h2>
            <ReleaseGrid releases={artist.releases} chronological />
        </section>
    {/if}
</div>

// frontend/src/app/artists/[slug]/page.tsx
import { IconLink } from "@/components/icon-link/IconLink";
import { ReleaseGrid } from "@/components/release/ReleaseGrid";
import { StrapiImage } from "@/components/strapi-image/StrapiImage";
import { content } from "@/lib/server/content";
import { PageProps } from "@/lib/types";
import { capitalize, md, mdi } from "@/lib/utils";
import type { NextPage } from "next";
import styles from "./Artist.module.scss";

/**
 * An individual artist's bio page
 */
const ArtistPage: NextPage<PageProps> = async ({ params }) => {
    const { slug } = await params;
    const artist = await content.artist(slug);// await cms.getArtist({ slug })
    // .catch(notFound);

    return (
        <main className="container">
            <section className="split-section">
                <StrapiImage
                    className="split-section__image"
                    image={artist.images[0]}
                    format="xlarge"
                    priority
                />

                <div className="split-section__content">
                    <h1 dangerouslySetInnerHTML={mdi(artist.name)} />
                    <div dangerouslySetInnerHTML={md(artist.bio)} />

                    {artist.links.length > 0 && (
                        <div className={styles.socialLinks}>
                            {artist.links.map(link => (
                                <IconLink
                                    key={link.link}
                                    href={link.link}
                                    icon={link.linktype}
                                    aria-label={`Visit the artist's ${capitalize(link.linktype)}`}
                                />
                            ))}
                        </div>
                    )}
                </div>
            </section>

            {artist.releases.length > 0 && (
                <section>
                    <h2>
                        Releases
                    </h2>
                    <ReleaseGrid
                        releases={artist.releases}
                        order="date"
                    />
                </section>
            )}
        </main>
    );
};

export default ArtistPage;
