// crafting-room-frontend/src/app/store/page.tsx
import { NextPage } from 'next';
import { notFound } from 'next/navigation';
import { ReleaseGrid } from '@/components/release/ReleaseGrid';
import { strapi } from '@/lib/server-utils';
import { mdi } from '@/lib/utils';

const StorePage: NextPage = async () => {
    const storePage = await strapi.getStorePage().catch(notFound);

    return (
        <div className='container'>
            <section>
                <h5>
                    More available on
                    {' '}
                    <a
                        href='https://craftingroomrecordings.bandcamp.com/'
                        target='_blank'
                        rel='noreferrer'
                    >
                        Bandcamp
                    </a>
                </h5>

                {storePage.attributes.groups.map(group => (
                    <section key={group.id}>
                        <h2 dangerouslySetInnerHTML={mdi(group.header)} />

                        <ReleaseGrid releases={group.releases.data} />
                    </section>
                ))}
            </section>
        </div>
    );
};

export default StorePage;

// site/src/routes/store/+page.svelte
<script lang="ts">
    import ReleaseGrid from "$lib/components/ReleaseGrid.svelte";
    import type { PageProps } from "./$types";

    let { data }: PageProps = $props();
    let { storePage } = data;
</script>

<main class="container flex flex-col gap-5">
    <span class="text-xl font-medium">
        More available on
        <a
            href="https://craftingroomrecordings.bandcamp.com/"
            target="_blank"
            rel="external"
            aria-label="Visit our Bandcamp"
        >
            Bandcamp
        </a>
    </span>

    {#each storePage.groups as group (group.id)}
        <h2>{group.header}</h2>
        <ReleaseGrid releases={group.releases} />
    {/each}
</main>
