// site/src/routes/store/+page.svelte
<script lang="ts">
    import ReleaseGrid from "$lib/components/ReleaseGrid.svelte";
    import type { PageProps } from "./$types";

    let { data }: PageProps = $props();
    let { storePage } = data;
</script>

<main class="container flex flex-col gap-5">
    <span class="text-xl font-medium">
        More available on
        <a
            href="https://craftingroomrecordings.bandcamp.com/"
            target="_blank"
            rel="external"
            aria-label="Visit our Bandcamp"
        >
            Bandcamp
        </a>
    </span>

    {#each storePage.groups as group (group.id)}
        <h2>{group.header}</h2>
        <ReleaseGrid releases={group.releases} />
    {/each}
</main>

// frontend/src/app/store/page.tsx
import type { NextPage } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import styles from "./Store.module.scss";
import { ReleaseGrid } from "@/components/release/ReleaseGrid";
import { cms } from "@/lib/server/services";
import { mdi } from "@/lib/utils";

const StorePage: NextPage = async () => {
    const storePage = await cms.getStorePage()
        .catch(notFound);

    return (
        <main className="container">
            <p className={styles.bandcampMessage}>
                More available on
                {" "}
                <Link
                    href="https://craftingroomrecordings.bandcamp.com/"
                    target="_blank"
                    rel="external"
                    aria-label="Visit our Bandcamp"
                >
                    Bandcamp
                </Link>
            </p>

            {storePage.attributes.groups.map(group => (
                <section key={group.id}>
                    <h2 dangerouslySetInnerHTML={mdi(group.header)} />
                    <ReleaseGrid releases={group.releases.data} />
                </section>
            ))}
        </main>
    );
};

export default StorePage;
