// frontend/src/app/news/[slug]/page.tsx
import { StrapiImage } from "@/components/strapi-image/StrapiImage";
import { content } from "@/lib/server/content";
import { PageProps } from "@/lib/types";
import { formatDate, md, mdi } from "@/lib/utils";
import type { NextPage } from "next";
import styles from "./Article.module.scss";

const ArticlePage: NextPage<PageProps> = async ({ params }) => {
    const { slug } = await params;
    const article = await content.article(slug);

    return (
        <main>
            <StrapiImage
                className={styles.image}
                image={article.images[0]}
                format="source"
                priority
            />

            <section className="container">
                <hgroup>
                    <h1 dangerouslySetInnerHTML={mdi(article.title)} />
                    <p className={styles.subtitle}>
                        <span className={styles.date}>
                            {formatDate(article.createdAt, "numeric")}
                        </span>
                        {" "}
                        ▸
                        {" "}
                        <span
                            className={styles.author}
                            dangerouslySetInnerHTML={mdi(article.author)}
                        />
                    </p>
                </hgroup>
                <div dangerouslySetInnerHTML={md(article.content)} />
            </section>
        </main>
    );
};

export default ArticlePage;

// site/src/routes/news/[slug]/+page.svelte
<script lang="ts">
    import Image from "$lib/components/Image.svelte";
    import { formatDate } from "$lib/utils";
    import type { PageProps } from "./$types";

    let { data }: PageProps = $props();
    let { article } = data;
</script>

<Image clazz="h-80 w-full" image={article.images[0]} format="source" />

<section class="container">
    <hgroup>
        <h1 class="mb-0">
            {article.title}
        </h1>
        <span class="flex gap-2 items-center">
            <span>
                {formatDate(article.createdAt, "numeric")}
            </span>
            ▸
            <span>{article.author}</span>
        </span>
    </hgroup>
    <div>
        {@html article.content}
    </div>
</section>
