// crafting-room-frontend/src/app/news/[slug]/page.tsx
import type { NextPage } from 'next';
import { notFound } from 'next/navigation';
import styles from './Article.module.scss';
import { cms } from '@/lib/server/services';
import { StrapiImage } from '@/components/strapi-image/StrapiImage';
import { mdi, md, formatDate } from '@/lib/utils';

type ServerProps = {
    params: { slug: string; };
};

const ArticlePage: NextPage<ServerProps> = async props => {
    const { slug } = props.params;
    const article = await cms.getArticle({ slug }).catch(notFound);

    return (
        <main>
            <StrapiImage
                className={styles.articleTopImage}
                image={article.attributes.images.data[0]}
                format='source'
                priority
            />

            <article className='container'>
                <hgroup>
                    <h1 dangerouslySetInnerHTML={mdi(article.attributes.title)} />
                    <p className={styles.subtitle}>
                        <span className={styles.date}>
                            {formatDate(article.attributes.createdAt, 'numeric')}
                        </span>
                        {' '}
                        ▸
                        {' '}
                        <span
                            className={styles.author}
                            dangerouslySetInnerHTML={mdi(article.attributes.author)}
                        />
                    </p>
                </hgroup>
                <div dangerouslySetInnerHTML={md(article.attributes.content)} />
            </article>
        </main>
    );
};

export default ArticlePage;

// site/src/routes/news/[slug]/+page.svelte
<script lang="ts">
    import Image from "$lib/components/Image.svelte";
    import { formatDate } from "$lib/utils";
    import type { PageProps } from "./$types";

    let { data }: PageProps = $props();
    let { article } = data;
</script>

<Image clazz="h-80 w-full" image={article.images[0]} format="source" />

<section class="container">
    <hgroup>
        <h1 class="mb-0">
            {article.title}
        </h1>
        <span class="flex gap-2 items-center">
            <span>
                {formatDate(article.createdAt, "numeric")}
            </span>
            ▸
            <span>{article.author}</span>
        </span>
    </hgroup>
    <div>
        {@html article.content}
    </div>
</section>
