// crafting-room-frontend/src/app/events/[slug]/page.tsx
import type { NextPage } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import styles from './Event.module.scss';
import { cms } from '@/lib/server/services';
import { SplitContentSection } from '@/components/split-content/SplitContent';
import { md, mdi } from '@/lib/utils/markdown';
import { formatDate, makeClass } from '@/lib/utils';
import { ArtistGrid } from '@/components/artist/ArtistGrid';

type ServerProps = {
    params: { slug: string; };
};

const EventPage: NextPage<ServerProps> = async props => {
    const { slug } = props.params;
    const event = await cms.getEvent({ slug }).catch(notFound);

    //TODO: get current date in uk time
    const currentDate = new Date();
    const eventDate = new Date(event.attributes.date);
    const eventIsInFuture = eventDate > currentDate;

    return (
        <main className='container'>
            <SplitContentSection image={event.attributes.image.data}>
                <hgroup>
                    <h1 dangerouslySetInnerHTML={mdi(event.attributes.title)} />
                    <p className={styles.subtitle}>
                        <span
                            className={styles.venue}
                            dangerouslySetInnerHTML={mdi(event.attributes.venue)}
                        />
                        {' '}
                        ▸
                        {' '}
                        <span className={styles.date}>
                            {formatDate(event.attributes.date, 'numeric')}
                        </span>
                    </p>
                </hgroup>

                {event.attributes.description && (
                    <div dangerouslySetInnerHTML={md(event.attributes.description)} />
                )}

                {event.attributes.link && eventIsInFuture && (
                    <Link
                        className={makeClass(
                            styles.book,
                            'button',
                            'button-primary'
                        )}
                        href={event.attributes.link}
                        target='_blank'
                        rel='external'
                    >
                        Book Tickets
                    </Link>
                )}
            </SplitContentSection>

            {event.attributes.artists && event.attributes.artists.data.length > 0 && (
                <section>
                    <h1>
                        Artists
                    </h1>
                    <ArtistGrid artists={event.attributes.artists.data} />
                </section>
            )}
        </main>
    );
};

export default EventPage;

// site/src/routes/events/[slug]/+page.svelte
<script lang="ts">
    import ArtistGrid from "$lib/components/ArtistGrid.svelte";
    import Image from "$lib/components/Image.svelte";
    import { formatDate } from "$lib/utils";
    import type { PageProps } from "./$types";

    let { data }: PageProps = $props();
    let { event } = data;

    const currentDate = new Date();
    const eventDate = new Date(event.date);
    const eventIsInFuture = eventDate > currentDate;
</script>

<main class="container">
    <section class="flex flex-col gap-5 sm:grid grid-cols-12 gap-x-10">
        <Image clazz="col-span-4" image={event.image} format="xlarge" />

        <div class="col-span-8 flex flex-col">
            <div>
                <h1>{event.title}</h1>
                <div class="flex flex-col md:flex-row gap-5 items-center">
                    <span class="mr-auto">
                        <span>{event.venue}</span>
                        ▸
                        <span>
                            {formatDate(event.date, "numeric")}
                        </span>
                    </span>
                    {#if event.link && eventIsInFuture}
                        <a
                            class="btn w-full sm:w-auto sm:mr-auto md:ml-auto"
                            href={event.link}
                            target="_blank"
                            rel="external"
                            aria-label="Book tickets for the event (external)"
                        >
                            Book Tickets
                        </a>
                    {/if}
                </div>
            </div>

            {@html event.description}
        </div>
    </section>

    {#if event.artists && event.artists?.length !== 0}
        <section>
            <h1>Artists</h1>
            <ArtistGrid artists={event.artists} />
        </section>
    {/if}
</main>
